version: '3.1'

services:
  list-loader:
    build:
      context: .
    dns:
      - 192.168.4.113
      - 192.168.4.30
      - 192.168.4.59
    environment:
      BLOCKLIST_API_BASE_URL: "${BLOCKLIST_API_BASE_URL}"
      BLOCKLIST_API_AUTH_TOKEN: "${BLOCKLIST_API_AUTH_TOKEN}"
    volumes:
     - ./history-files:/opt/history-files
